version: '3'
services:
  shop_api:
    build:
      context: .
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    depends_on:
      - shop_db
  shop_db:
    image: "postgres:14"
    environment:
      - POSTGRES_DB=shop_api_db
      - POSTGRES_USER=shop_api_user
      - POSTGRES_PASSWORD=123
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
volumes:
  pgdata: